include ../make/Makefile.lib.options

SOURCES = 3d.cc bits.cc control_general.cc kalman.cc models_base.cc models_double.cc feature.cc scene_dsm.cc scene_single.cc sim_or_rob.cc simul.cc waypoints.cc postscript.cc
EXTRAHEADERS = general_headers.h scene_base.h

include ../make/Makefile.lib.master
