include ../make/Makefile.lib.options

SOURCES = waypoint_browser.cc formbrowser.c scene_inspect.cc forminspect.c kalman_form.cc formkalman.c
EXTRACFLAGS = -I$(XFORMSINCDIR)

include ../make/Makefile.lib.master
